apiVersion: v1
kind: Namespace
metadata:
  name: service4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4-app
  namespace: service4
  labels:
    app: service4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service4-service
  namespace: service4
spec:
  selector:
    app: service4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


