apiVersion: v1
kind: Namespace
metadata:
  name: service1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-app
  namespace: service1
  labels:
    app: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: service1
spec:
  selector:
    app: service1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


