apiVersion: v1
kind: Namespace
metadata:
  name: service2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-app
  namespace: service2
  labels:
    app: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service2-service
  namespace: service2
spec:
  selector:
    app: service2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


